/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoCapgemini;

import controller.ProjectController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import util.ConnectionFactory;

public class App {
  
    public static void main(String[] args) {
     
   
    }
}
